/**
 * Mock Data Configuration — AUTO-GENERATED by design-codegen
 *
 * This file is generated from the design schema's ApiDataSource.mock config.
 * DO NOT EDIT manually — changes will be overwritten on next codegen run.
 *
 * Structure:
 *   - mockConfigs: Record<dataSourceId, MockConfig>
 *     - scenarios: MockScenario[]
 *     - activeScenarioId: string (default from schema)
 *   - endpointMap: Record<dataSourceId, urlPath> — for URL matching in interceptor
 *
 * @see /features/design-schema/src/types/dataSource.ts — MockScenario / MockConfig
 */

import { initMock, _setEndpointMap } from '@/utils/mock-manager';

// ─── Mock Scenarios ──────────────────────────────────────────

const mockConfigs: Record<string, {
  scenarios: Array<{
    id: string;
    name: string;
    description?: string;
    statusCode: number;
    delay: number;
    isTimeout?: boolean;
    responseBody: unknown;
  }>;
  activeScenarioId: string;
}> = {
  "chat-list": {
    "scenarios": [
      {
        "id": "sc-default",
        "name": "默认 4 条种子",
        "description": "",
        "statusCode": 200,
        "delay": 300,
        "isTimeout": false,
        "responseBody": [
          {
            "id": "1",
            "role": "assistant",
            "text": "Hi! I'm your AI music assistant. What would you like to create today?"
          },
          {
            "id": "2",
            "role": "user",
            "text": "Create a lo-fi beat for studying"
          },
          {
            "id": "3",
            "role": "assistant",
            "text": "Great! I'll craft a chill lo-fi track at 70 BPM with soft piano and rain ambience."
          },
          {
            "id": "4",
            "role": "user",
            "text": "Perfect, make it 2 minutes long"
          },
          {
            "id": "5",
            "role": "assistant",
            "text": "Got it! 2 minutes of lo-fi goodness coming right up. Adding some vinyl crackle for warmth."
          },
          {
            "id": "6",
            "role": "user",
            "text": "Can you add some jazz guitar?"
          },
          {
            "id": "7",
            "role": "assistant",
            "text": "Absolutely! I'll layer in some mellow jazz guitar chords with a slight reverb."
          },
          {
            "id": "8",
            "role": "user",
            "text": "How about a saxophone solo in the middle?"
          },
          {
            "id": "9",
            "role": "assistant",
            "text": "Nice idea! I'll add a smooth saxophone solo around the 1-minute mark."
          },
          {
            "id": "10",
            "role": "user",
            "text": "Love it! Can we also try a hip-hop version?"
          },
          {
            "id": "11",
            "role": "assistant",
            "text": "Sure! I'll create a hip-hop remix with boom-bap drums and a heavier bass line."
          },
          {
            "id": "12",
            "role": "user",
            "text": "Make the drums punchier"
          },
          {
            "id": "13",
            "role": "assistant",
            "text": "Done! Boosted the kick and snare with sidechain compression for that pumping effect."
          },
          {
            "id": "14",
            "role": "user",
            "text": "What BPM is the hip-hop version?"
          },
          {
            "id": "15",
            "role": "assistant",
            "text": "The hip-hop version is at 90 BPM. Want me to speed it up?"
          },
          {
            "id": "16",
            "role": "user",
            "text": "No, 90 is perfect. Can you add vocals?"
          },
          {
            "id": "17",
            "role": "assistant",
            "text": "I can add vocal chops and harmonized samples. Full vocal generation is coming soon!"
          },
          {
            "id": "18",
            "role": "user",
            "text": "Add the vocal chops then"
          },
          {
            "id": "19",
            "role": "assistant",
            "text": "Added! Pitched vocal chops on beats 2 and 4 with a reverb tail."
          },
          {
            "id": "20",
            "role": "user",
            "text": "This is amazing, save both versions!"
          }
        ]
      }
    ],
    "activeScenarioId": "sc-default"
  },
  "chat-send": {
    "scenarios": [
      {
        "id": "sc-success",
        "name": "模拟 AI 回复 1.2s",
        "description": "",
        "statusCode": 200,
        "delay": 1200,
        "isTimeout": false,
        "responseBody": {
          "aiReply": {
            "id": "a_new",
            "role": "assistant",
            "text": "Got it! I will craft something for: '{{ params.text }}'."
          },
          "userMessage": {
            "id": "u_new",
            "role": "user",
            "text": "{{ params.text }}"
          }
        }
      }
    ],
    "activeScenarioId": "sc-success"
  }
};

// ─── Endpoint → DataSource mapping for URL matching ──────
const endpointMap: Record<string, string> = {
  "chat-list": "/chat/list",
  "chat-send": "/chat/send"
};

// ─── Initialize ────────────────────────────────────────────
initMock(mockConfigs);
_setEndpointMap(endpointMap);

export { mockConfigs, endpointMap };
